Repository fluxcd/notification-controller, pull requests merged in 2020-07, with the labels that each got.

#1 Notification API RFC
  PROJECT
  api/v1alpha1/alert_types.go
  api/v1alpha1/condition_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/provider_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/notification.fluxcd.io_alerts.yaml
  config/crd/bases/notification.fluxcd.io_providers.yaml
  config/crd/kustomization.yaml
  config/rbac/alert_editor_role.yaml
  config/rbac/alert_viewer_role.yaml
  config/rbac/provider_editor_role.yaml
  config/rbac/provider_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/notification_v1alpha1_alert.yaml
  config/samples/notification_v1alpha1_provider.yaml
  controllers/alert_controller.go
  controllers/provider_controller.go
  controllers/suite_test.go
  docs/spec/README.md
  docs/spec/v1alpha1/alert.md
  docs/spec/v1alpha1/event.md
  docs/spec/v1alpha1/provider.md
  go.mod
  main.go
Labels: area/docs

#6 Add wildcard support
  config/samples/notification_v1alpha1_alert.yaml
  docs/spec/README.md
  docs/spec/v1alpha1/alert.md
  docs/spec/v1alpha1/provider.md
  internal/server/handlers.go
Labels: enhancement

#8 Receiver API spec
  docs/spec/v1alpha1/receiver.md
Labels: area/docs

#11 Rename webhook alert provider to generic
  api/v1alpha1/provider_types.go
  config/crd/bases/notification.fluxcd.io_providers.yaml
  docs/spec/v1alpha1/provider.md
  internal/notifier/factory.go
Labels: area/alerting, area/docs

#14 Setup production logging
  config/manager/deployment.yaml
  go.mod
  main.go
Labels: enhancement

#15 Update source-controller to v0.0.5
  go.mod
  go.sum
  internal/server/receiver_handlers.go
Labels: area/receiver, enhancement

#17 Remove namespace scope from deployment
  config/manager/deployment.yaml
Labels: area/alerting

#19 Lookup alerts at cluster level
  internal/server/event_handlers.go
Labels: area/alerting, enhancement

#20 Normalise controller logs
  controllers/alert_controller.go
  controllers/provider_controller.go
  controllers/receiver_controller.go
Labels: enhancement

#22 Upgrade CRDs to apiextensions.k8s.io/v1
  .github/workflows/e2e.yaml
  Dockerfile
  Makefile
  config/crd/bases/notification.fluxcd.io_alerts.yaml
  config/crd/bases/notification.fluxcd.io_providers.yaml
  config/crd/bases/notification.fluxcd.io_receivers.yaml
  go.mod
  go.sum
Labels: enhancement

#28 Change CRD domain to 'notification.toolkit.fluxcd.io'
  CHANGELOG.md
  PROJECT
  README.md
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  config/crd/kustomization.yaml
  config/rbac/alert_editor_role.yaml
  config/rbac/alert_viewer_role.yaml
  config/rbac/provider_editor_role.yaml
  config/rbac/provider_viewer_role.yaml
  config/rbac/receiver_editor_role.yaml
  config/rbac/receiver_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/notification_v1alpha1_alert.yaml
  config/samples/notification_v1alpha1_provider.yaml
  config/samples/notification_v1alpha1_receiver.yaml
  controllers/alert_controller.go
  controllers/provider_controller.go
  controllers/receiver_controller.go
  docs/api/notification.md
  docs/spec/README.md
  docs/spec/v1alpha1/README.md
  docs/spec/v1alpha1/alert.md
  docs/spec/v1alpha1/provider.md
  docs/spec/v1alpha1/receiver.md
  go.mod
  go.sum
  internal/notifier/client_test.go
  internal/notifier/discord.go
  internal/notifier/forwarder.go
  internal/notifier/forwarder_test.go
  internal/notifier/rocket.go
  internal/notifier/slack.go
  internal/notifier/teams.go
  internal/server/event_handlers.go
  internal/server/receiver_handlers.go
Labels: enhancement
