Repository fluxcd/notification-controller, pull requests merged in 2020-09, with the labels that each got.

#36 Configure manager logging and set level to info
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#37 Use runtime pkg and bump build-push-action version
  .github/workflows/release.yml
  go.mod
  go.sum
  main.go
Labels: area/build

#38 Make the api package a dedicated module
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
Labels: area/build

#41 Add watch all namespaces flag
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#46 Add opencontainers source label
  Dockerfile
Labels: area/build

#48 ci: add sanity check for container images
  .github/workflows/release.yml
Labels: area/build

#49 Add commit status providers to API spec
  docs/spec/README.md
  docs/spec/v1alpha1/provider.md
Labels: area/docs

#50 Publish ARM v7/v8 multi-arch image to GHCR
  .github/workflows/release.yml
Labels: area/build

#51 Add support for S3 buckets to alerts and receivers
  api/v1alpha1/reference_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  docs/spec/v1alpha1/alert.md
  docs/spec/v1alpha1/receiver.md
  go.mod
  go.sum
  internal/server/receiver_handlers.go
Labels: area/alerting, area/docs, area/receiver
