Repository fluxcd/notification-controller, pull requests merged in 2020-11, with the labels that each got.

#74 Add validation for providers and alerts
  controllers/alert_controller.go
  controllers/provider_controller.go
  internal/server/event_handlers.go
Labels: area/alerting, enhancement

#77 Update engineerd/setup-kind to v0.5.0
  .github/workflows/e2e.yaml
Labels: area/build

#88 Fix "Notification API reference" title
  docs/api/notification.md
  hack/api-docs/template/pkg.tpl
Labels: area/docs, bug

#89 Add readiness/liveness probes
  config/manager/deployment.yaml
  go.mod
  go.sum
  main.go
Labels: enhancement
