Repository fluxcd/notification-controller, pull requests merged in 2021-03, with the labels that each got.

#151 Uses unstructured client to annotate object
  docs/spec/v1beta1/receiver.md
  go.mod
  go.sum
  internal/server/receiver_handlers.go
  main.go
Labels: area/receiver, enhancement

#153 Add ACR webhook receiver
  api/v1beta1/receiver_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  docs/spec/v1beta1/receiver.md
  internal/server/receiver_handlers.go
Labels: area/receiver, enhancement

#156 Use controller-runtime structured logging
  internal/server/event_handlers.go
  internal/server/receiver_handlers.go
Labels: enhancement

#157 Update dependencies
  .github/workflows/fossa.yml
  .github/workflows/scan.yml
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#164 Record suspension metrics
  controllers/alert_controller.go
  controllers/receiver_controller.go
  go.mod
  go.sum
Labels: enhancement

#162 Add support for GitHub enterprise commit status
  internal/notifier/github.go
  internal/notifier/github_test.go
Labels: area/alerting

#166 Use deepcopy method for event
  controllers/suite_test.go
  go.mod
  go.sum
  internal/notifier/azure_devops.go
  internal/notifier/bitbucket.go
  internal/notifier/client_test.go
  internal/notifier/discord.go
  internal/notifier/forwarder.go
  internal/notifier/forwarder_test.go
  internal/notifier/github.go
  internal/notifier/gitlab.go
  internal/notifier/google_chat.go
  internal/notifier/nop.go
  internal/notifier/notifier.go
  internal/notifier/rocket.go
  internal/notifier/slack.go
  internal/notifier/teams.go
  internal/notifier/util.go
  internal/notifier/util_test.go
  internal/server/event_handlers.go
Labels: area/alerting

#168 Add support for Webex as an alert provider
  api/v1beta1/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/spec/v1beta1/provider.md
  internal/notifier/factory.go
  internal/notifier/webex.go
  internal/notifier/webex_test.go
Labels: area/alerting, enhancement

#169 Remove filter for progressing events in googlechat
  internal/notifier/google_chat.go
Labels: area/alerting

#170 Set leader election deadline to 30s
  go.mod
  go.sum
  main.go
Labels: enhancement

#174 fix: use sha1 sum as value for key in bitbucket api requests
  internal/notifier/bitbucket.go
  internal/notifier/util.go
  internal/notifier/util_test.go
Labels: area/alerting

#176 Add support for Sentry provider
  api/v1beta1/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/spec/v1beta1/provider.md
  go.mod
  go.sum
  internal/notifier/factory.go
  internal/notifier/sentry.go
  internal/notifier/sentry_test.go
Labels: area/alerting, enhancement

#171 Add observedGeneration to status of alert and receivers
  api/v1beta1/alert_types.go
  api/v1beta1/receiver_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  controllers/alert_controller.go
  controllers/provider_controller.go
  controllers/receiver_controller.go
  docs/api/notification.md
Labels: area/alerting, area/receiver, enhancement
