Repository fluxcd/notification-controller, pull requests merged in 2021-07, with the labels that each got.

#219 Fix a few typos
  docs/spec/v1beta1/receiver.md
Labels: area/docs

#221 providers/sentry: fix default HTTP Transport causing panic
  internal/notifier/sentry.go
Labels: area/alerting, bug

#223 providers/sentry: add environment support
  docs/spec/v1beta1/provider.md
  internal/notifier/factory.go
  internal/notifier/sentry.go
  internal/notifier/sentry_test.go
Labels: area/alerting, enhancement
