Repository fluxcd/notification-controller, pull requests merged in 2021-11, with the labels that each got.

#280 Use x509 certificate for Webex
  internal/notifier/webex.go
Labels: area/alerting

#287 Fix nil dereference err in AlertManager
  internal/notifier/alertmanager.go
Labels: bug, area/alerting

#282 Use conditions helper in reconciler (kstatus compat)
  api/v1beta1/alert_types.go
  api/v1beta1/condition_types.go
  api/v1beta1/provider_types.go
  api/v1beta1/receiver_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  controllers/alert_controller.go
  controllers/provider_controller.go
  controllers/receiver_controller.go
  controllers/suite_test.go
  docs/api/notification.md
  go.mod
  go.sum
  internal/server/event_handlers.go
  internal/server/receiver_handlers.go
  main.go
Labels: enhancement

#289 Update controller-runtime to v0.10.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#293 spec: improve wording around Slack App integration
  docs/spec/v1beta1/provider.md
Labels: area/docs
