Repository fluxcd/notification-controller, pull requests merged in 2021-02, with the labels that each got.

#136 Enable pprof endpoints on metrics server
  go.mod
  go.sum
  main.go
Labels: area/build

#138 Implement regex exclusions for alerts
  api/v1beta1/alert_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  docs/api/notification.md
  docs/spec/v1beta1/alert.md
  internal/server/event_handlers.go
Labels: area/alerting, enhancement

#140 Update fluxcd/pkg/apis/meta to v0.8.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#141 Fixing openssl oneliner to work on macOS and Linux
  docs/spec/v1beta1/receiver.md
Labels: area/docs

#144 Fix alerts regex filtering
  internal/server/event_handlers.go
Labels: area/alerting, bug

#146 Refactor release workflow
  .github/workflows/release.yml
Labels: area/build

#147 Update dependencies
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  docs/api/notification.md
  go.mod
  go.sum
  hack/api-docs/config.json
Labels: area/build
