Repository fluxcd/notification-controller, pull requests merged in 2022-01, with the labels that each got.

#300 Update docs for telegram
  docs/spec/v1beta1/provider.md
Labels: area/docs, area/alerting

#301 Update dependencies (fix CVE-2021-43565)
  go.mod
  go.sum
  internal/notifier/github.go
  internal/notifier/github_test.go
  internal/server/receiver_handlers.go
Labels: area/build

#303 Downgrade fluxcd/pkg/apis/meta to v0.10.2
  api/go.mod
  api/go.sum
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  go.sum
Labels: area/build

#298 Add timestamp as label for alertmanager
  docs/spec/v1beta1/provider.md
  internal/notifier/alertmanager.go
Labels: area/alerting

#306 Add fuzz testing for notifiers
  .github/workflows/cifuzz.yaml
  .gitignore
  Makefile
  go.mod
  go.sum
  internal/notifier/alertmanager_test.go
  tests/fuzz/Dockerfile.builder
  tests/fuzz/alertmanager_fuzzer.go
  tests/fuzz/azure_devops_fuzzer.go
  tests/fuzz/bitbucket_fuzzer.go
  tests/fuzz/discord_fuzzer.go
  tests/fuzz/forwarder_fuzzer.go
  tests/fuzz/github_fuzzer.go
  tests/fuzz/gitlab_fuzzer.go
  tests/fuzz/go.mod
  tests/fuzz/google_chat_fuzzer.go
  tests/fuzz/lark_fuzzer.go
  tests/fuzz/matrix_fuzzer.go
  tests/fuzz/opsgenie_fuzzer.go
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/oss_fuzz_run.sh
  tests/fuzz/rocket_fuzzer.go
  tests/fuzz/slack_fuzzer.go
  tests/fuzz/teams_fuzzer.go
  tests/fuzz/util_fuzzer.go
  tests/fuzz/webex_fuzzer.go
Labels: area/build

#308 Add documentation for gitea
  docs/spec/v1beta1/receiver.md
Labels: area/docs, area/receiver

#307 Fix makefile envtest and controller-gen usage
  .github/workflows/e2e.yaml
  .gitignore
  Makefile
Labels: area/build

#309 Update development documentation
  DEVELOPMENT.md
Labels: area/docs

#310 Replace cifuzz with custom smoke test
  .github/workflows/cifuzz.yaml
  Makefile
Labels: area/build

#314 Publish SBOM and sign release artifacts
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  .goreleaser.yaml
Labels: enhancement, area/build

#317 Pass headers to generic provider through secretRef
  .github/workflows/e2e.yaml
  config/samples/notification_v1beta1_alert.yaml
  config/samples/notification_v1beta1_provider.yaml
  controllers/provider_controller.go
  docs/spec/v1beta1/provider.md
  go.mod
  internal/notifier/factory.go
  internal/notifier/forwarder.go
  internal/notifier/forwarder_test.go
  internal/server/event_handlers.go
  tests/fuzz/forwarder_fuzzer.go
Labels: enhancement, area/alerting

#319 Allow disabling cross-namespace event sources
  api/go.mod
  api/go.sum
  controllers/event_handling_test.go
  controllers/suite_test.go
  docs/spec/v1beta1/alert.md
  go.mod
  go.sum
  internal/server/event_handlers.go
  internal/server/event_server.go
  main.go
Labels: enhancement, area/alerting
