Repository fluxcd/notification-controller, pull requests merged in 2022-04, with the labels that each got.

#357 update toolkit.fluxcd.io docs link
  README.md
Labels: area/docs

#361 Return err on invalid UTF-8 character in token
  internal/server/event_handlers.go
  internal/server/event_handlers_test.go
Labels: area/alerting

#367 Update golang.org/x/crypto
  go.mod
  go.sum
Labels: area/build

#366 Check for duplicate commit status in Bitbucket
  internal/notifier/bitbucket.go
Labels: enhancement
