Repository fluxcd/notification-controller, pull requests merged in 2022-03, with the labels that each got.

#346 Update dependencies
  api/go.mod
  api/go.sum
  controllers/suite_test.go
  go.mod
  go.sum
Labels: area/build

#347 Cleanup metadata fields before alerting
  Makefile
  api/go.sum
  go.sum
  internal/server/event_handlers.go
Labels: area/alerting

#350 Filter event metadata based on the object group
  internal/server/event_handlers.go
Labels: area/alerting

#354 Align version of dependencies when Fuzzing
  tests/fuzz/oss_fuzz_build.sh
Labels: area/build

#352 Update the webex notification provider and markdown
  docs/spec/v1beta1/provider.md
  internal/notifier/factory.go
  internal/notifier/webex.go
  internal/notifier/webex_test.go
  tests/fuzz/webex_fuzzer.go
Labels: enhancement, area/alerting

#355 update fluxcd/pkg/runtime to v0.13.4
  go.mod
  go.sum
Labels: area/build
