Repository fluxcd/notification-controller, pull requests merged in 2022-05, with the labels that each got.

#370 Add docs for Microsoft Teams
  docs/spec/v1beta1/provider.md
Labels: area/docs

#371 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#369 Add GitHub dispatch provider
  api/v1beta1/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/spec/v1beta1/provider.md
  internal/notifier/factory.go
  internal/notifier/github_dispatch.go
  internal/notifier/github_dispatch_test.go
Labels: enhancement, area/alerting

#375 Better error messages for alert providers
  internal/notifier/alertmanager.go
  internal/notifier/discord.go
  internal/notifier/matrix.go
  internal/notifier/opsgenie.go
  internal/notifier/rocket.go
  internal/notifier/slack.go
  internal/notifier/teams.go
  internal/notifier/webex.go
Labels: enhancement, area/alerting

#373 Update dependencies
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#379 Update GitHub actions
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#380 Release v0.24.0
  CHANGELOG.md
  config/manager/kustomization.yaml
  go.mod
Labels: area/build
