Repository fluxcd/notification-controller, pull requests merged in 2022-02, with the labels that each got.

#321 docs: update alert provider types
  docs/spec/v1beta1/provider.md
Labels: area/docs

#322 Add support for Grafana annotations API
  api/v1beta1/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/spec/v1beta1/provider.md
  internal/notifier/factory.go
  internal/notifier/grafana.go
  internal/notifier/grafana_test.go
Labels: enhancement, area/alerting

#324 discord: Remove username and channel requirements
  internal/notifier/discord.go
Labels: area/alerting

#330 Switch to controller-runtime metadata client
  controllers/receiver_controller_test.go
  internal/server/event_handlers.go
  internal/server/receiver_handlers.go
Labels: enhancement

#333 Update dependencies
  go.mod
  go.sum
Labels: area/build

#331 Allow the proxy address to specified in the Kubernetes Secret from Alert `spec.secretRef`
  controllers/provider_controller.go
  docs/spec/v1beta1/provider.md
  internal/server/event_handlers.go
Labels: enhancement, area/alerting

#334 Add basic auth support to grafana provider
  controllers/provider_controller.go
  docs/spec/v1beta1/provider.md
  internal/notifier/factory.go
  internal/notifier/grafana.go
  internal/notifier/grafana_test.go
  internal/notifier/util.go
  internal/notifier/util_test.go
  internal/server/event_handlers.go
Labels: enhancement, area/alerting

#338 Update dependencies
  go.mod
  go.sum
Labels: area/build
