Repository fluxcd/notification-controller, pull requests merged in 2022-07, with the labels that each got.

#387 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#390 Force github.com/emicklei/go-restful to v2.16.0
  go.mod
  go.sum
Labels: area/build

#394 Add missing language to fenced code block
  docs/spec/v1beta1/provider.md
Labels: area/docs

#385 Add context to Post function
  internal/notifier/alertmanager.go
  internal/notifier/alertmanager_test.go
  internal/notifier/azure_devops.go
  internal/notifier/azure_eventhub.go
  internal/notifier/bitbucket.go
  internal/notifier/discord.go
  internal/notifier/discord_test.go
  internal/notifier/forwarder.go
  internal/notifier/forwarder_test.go
  internal/notifier/github.go
  internal/notifier/github_dispatch.go
  internal/notifier/github_dispatch_test.go
  internal/notifier/gitlab.go
  internal/notifier/google_chat.go
  internal/notifier/google_chat_test.go
  internal/notifier/grafana.go
  internal/notifier/grafana_test.go
  internal/notifier/lark.go
  internal/notifier/lark_test.go
  internal/notifier/matrix.go
  internal/notifier/nop.go
  internal/notifier/notifier.go
  internal/notifier/opsgenie.go
  internal/notifier/opsgenie_test.go
  internal/notifier/rocket.go
  internal/notifier/rocket_test.go
  internal/notifier/sentry.go
  internal/notifier/slack.go
  internal/notifier/slack_test.go
  internal/notifier/teams.go
  internal/notifier/teams_test.go
  internal/notifier/telegram.go
  internal/notifier/webex.go
  internal/notifier/webex_test.go
  internal/server/event_handlers.go
  tests/fuzz/alertmanager_fuzzer.go
  tests/fuzz/azure_devops_fuzzer.go
  tests/fuzz/bitbucket_fuzzer.go
  tests/fuzz/discord_fuzzer.go
  tests/fuzz/forwarder_fuzzer.go
  tests/fuzz/github_fuzzer.go
  tests/fuzz/gitlab_fuzzer.go
  tests/fuzz/google_chat_fuzzer.go
  tests/fuzz/lark_fuzzer.go
  tests/fuzz/matrix_fuzzer.go
  tests/fuzz/opsgenie_fuzzer.go
  tests/fuzz/rocket_fuzzer.go
  tests/fuzz/slack_fuzzer.go
  tests/fuzz/teams_fuzzer.go
  tests/fuzz/webex_fuzzer.go
Labels: area/alerting
