Repository fluxcd/notification-controller, pull requests merged in 2023-08, with the labels that each got.

#590 Use TrimPrefix instead of TrimLeft
  internal/server/receiver_handlers.go
Labels: bug, area/receiver, backport:release/v1.0.x

#583 Clarify permission requirements for Gitea provider token
  docs/spec/v1beta2/providers.md
Labels: area/docs, area/alerting, backport:release/v1.0.x

#600 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#592 feat: add DataDog notification provider
  api/v1beta2/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/spec/v1beta2/providers.md
  go.mod
  go.sum
  internal/notifier/datadog.go
  internal/notifier/datadog_fuzz_test.go
  internal/notifier/datadog_test.go
  internal/notifier/factory.go
  internal/notifier/util.go
Labels: enhancement, area/alerting

#603 Remove checks for empty user and channel parameters in Rocket notifier
  internal/notifier/rocket.go
  internal/notifier/rocket_test.go
Labels: area/alerting

#606 Update dependencies
  go.mod
  go.sum
Labels: dependencies
