Repository fluxcd/notification-controller, pull requests merged in 2023-06, with the labels that each got.

#544 Reduce logging repeated code in event server
  internal/server/event_handlers.go
  internal/server/event_handlers_test.go
  internal/server/event_server.go
Labels: enhancement, area/alerting

#543 Add Provider for Google Pub/Sub Topic
  api/v1beta2/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/spec/v1beta2/providers.md
  go.mod
  go.sum
  internal/notifier/factory.go
  internal/notifier/google_pubsub.go
  internal/notifier/google_pubsub_test.go
Labels: area/alerting

#557 docs: fix generic webhook example
  docs/spec/v1beta2/providers.md
Labels: area/docs

#556 Improve error messages in Gitea notifier
  internal/notifier/gitea.go
  internal/notifier/util.go
Labels: area/alerting

#559 Add SLSA3 generators to release workflow
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: area/build

#562 Align `go.mod` version with Kubernetes (Go 1.20)
  api/go.mod
  go.mod
  tests/fuzz/Dockerfile.builder
Labels: area/build

#563 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/notifier/github.go
  internal/notifier/github_dispatch.go
  internal/notifier/github_test.go
  internal/server/receiver_handler_test.go
  internal/server/receiver_handlers.go
Labels: dependencies

#527 Add support for PagerDuty
  api/v1beta2/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/spec/v1beta2/providers.md
  go.mod
  go.sum
  internal/notifier/factory.go
  internal/notifier/pagerduty.go
  internal/notifier/pagerduty_fuzz_test.go
  internal/notifier/pagerduty_test.go
Labels: enhancement, area/alerting

#566 Add backport GitHub Action workflow
  .github/dependabot.yaml
  .github/labels.yaml
  .github/workflows/backport.yaml
  .github/workflows/sync-labels.yaml
Labels: area/build
