Repository fluxcd/notification-controller, pull requests merged in 2023-05, with the labels that each got.

#515 Add InclusionList to Alert CRD
  api/v1beta2/alert_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  docs/api/v1beta2/notification.md
  docs/spec/v1beta2/alerts.md
  internal/controllers/alert_controller_test.go
  internal/server/event_handlers.go
Labels: enhancement, area/alerting

#506 index receivers using webhook path as key
  internal/controllers/receiver_controller.go
  internal/controllers/receiver_controller_test.go
  internal/server/receiver_handler_test.go
  internal/server/receiver_handlers.go
Labels: area/receiver

#520 Update dependencies
  go.mod
  go.sum
  internal/notifier/github.go
  internal/notifier/github_dispatch.go
  internal/notifier/github_test.go
  internal/server/receiver_handler_test.go
  internal/server/receiver_handlers.go
Labels: dependencies

#524 Update Alpine to 3.18
  Dockerfile
Labels: area/build

#519 Add event metadata field to Alert spec
  api/v1beta2/alert_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  docs/api/v1beta2/notification.md
  docs/spec/v1beta2/alerts.md
  internal/server/event_handlers.go
Labels: enhancement, area/alerting

#532 Update dependencies and Kubernetes to 1.27.2
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controllers/alert_controller.go
  internal/controllers/provider_controller.go
  internal/controllers/receiver_controller.go
  internal/controllers/suite_test.go
  main.go
Labels: dependencies

#530 Include eventv1.MetaTokenKey on event rate limiting key calculation
  internal/server/event_server.go
  internal/server/event_server_test.go
Labels: enhancement

#529 Fix Alert .spec.eventMetadata behavior
  api/v1beta2/alert_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  docs/api/v1beta2/notification.md
  docs/spec/v1beta2/alerts.md
  internal/server/event_handlers.go
  internal/server/event_handlers_test.go
  internal/server/event_server.go
Labels: bug

#534 Prefix event key attributes with identifier
  internal/server/event_server.go
Labels: enhancement, area/alerting

#535 Update workflows and enable dependabot
  .github/dependabot.yaml
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yml
Labels: area/build
