Repository fluxcd/notification-controller, pull requests merged in 2023-12, with the labels that each got.

#651 Add Provider for NATS Subject
  api/v1beta3/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/spec/v1beta3/providers.md
  go.mod
  go.sum
  internal/notifier/factory.go
  internal/notifier/nats.go
  internal/notifier/nats_test.go
Labels: enhancement, area/alerting

#664 Replace whilp/git-urls module by chainguard-dev/git-urls
  go.mod
  go.sum
  internal/notifier/util.go
Labels: dependencies, backport:release/v1.2.x

#668 Update dependencies
  go.mod
  go.sum
Labels: dependencies, backport:release/v1.2.x

#673 build: update Alpine to 3.19
  Dockerfile
Labels: area/ci, dependencies, backport:release/v1.2.x

#676 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies, backport:release/v1.2.x
