Repository fluxcd/notification-controller, pull requests merged in 2023-07, with the labels that each got.

#569 Update GCP dependencies
  go.mod
  go.sum
Labels: dependencies

#565 Lift HTTP/S validation from Provider spec.address
  api/v1beta2/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  docs/api/v1beta2/notification.md
  docs/spec/v1beta2/providers.md
Labels: area/api

#570 ci: various workflow changes
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yml
Labels: area/ci

#573 ci: various workflow changes
  .github/dependabot.yaml
  .github/workflows/backport.yaml
Labels: area/ci

#574 Fix GHA backport.yaml workflow job perms
  .github/workflows/backport.yaml
  .github/workflows/release.yml
Labels: area/ci

#585 change key type to []byte in provider spec docs
  docs/spec/v1beta2/providers.md
Labels: area/docs
