Repository fluxcd/notification-controller, pull requests merged in 2023-03, with the labels that each got.

#484 build: update release workflow
  .github/workflows/release.yml
  .github/workflows/scan.yml
Labels: area/build

#483 Update Go to 1.20
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yml
  Dockerfile
  Makefile
Labels: area/build

#485 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#486 Use `logger.SetLogger` to also configure `klog`
  go.mod
  go.sum
  main.go
Labels: enhancement

#487 release: pass `--yes` to cosign in signs
  .goreleaser.yaml
Labels: area/build

#482 feat: support multi receiver by matchLabels
  api/v1beta2/reference_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  docs/api/notification.md
  docs/spec/v1beta2/receivers.md
  internal/server/receiver_handler_test.go
  internal/server/receiver_handlers.go
Labels: enhancement, area/receiver, on-hold

#501 un-document receivers.spec.resources.matchLabels
  api/v1beta2/reference_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  docs/api/notification.md
  docs/spec/v1beta2/receivers.md
Labels: area/docs
