Repository fluxcd/notification-controller, pull requests merged in 2024-08, with the labels that each got.

#905 Update dependencies to Kubernetes v1.31.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/controller/receiver_controller.go
  internal/notifier/github.go
  internal/notifier/github_dispatch.go
  internal/notifier/github_test.go
  internal/server/receiver_handler_test.go
  internal/server/receiver_handlers.go
Labels: dependencies

#907 Build with Go 1.23
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yml
  DEVELOPMENT.md
  Dockerfile
  tests/fuzz/Dockerfile.builder
Labels: area/ci

#841 New flag to disable detailed metrics for path
  internal/controller/receiver_controller_test.go
  internal/server/event_server.go
  internal/server/event_server_test.go
  internal/server/receiver_server.go
  main.go
Labels: enhancement
