Repository fluxcd/notification-controller, pull requests merged in 2024-01, with the labels that each got.

#713 ci: Enable dependabot `gomod` updates
  .github/dependabot.yaml
Labels: area/ci

#716 dependabot: Ignore `go-logr` package
  .github/dependabot.yaml
Labels: area/ci

#722 Fix BitBucket status update panic
  internal/notifier/bitbucketserver.go
Labels: backport:release/v1.2.x

#727 [release/v1.2.x] Backport workflows dependency updates from the main branch
  .github/workflows/backport.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
Labels: dependencies
