Repository fluxcd/notification-controller, pull requests merged in 2024-04, with the labels that each got.

#785 Update dependencies to Go 1.22 and Kubernetes 1.29.3
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yml
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  tests/fuzz/Dockerfile.builder
Labels: dependencies

#789 Sanitize provider data loaded from secret
  internal/server/event_handlers.go
Labels: area/alerting

#790 Use `password` as fallback for the Git provider `token` auth
  internal/notifier/factory.go
Labels: area/alerting

#747 Add support for Bitbucket Context path
  docs/spec/v1beta2/providers.md
  docs/spec/v1beta3/providers.md
  internal/notifier/bitbucketserver.go
  internal/notifier/bitbucketserver_test.go
Labels: enhancement, area/alerting

#809 Update dependencies to Kubernetes 1.30
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
  go.mod
  go.sum
Labels: dependencies

#795 Alertmanager: Change timestamp label to .StartsAt
  docs/spec/v1beta3/providers.md
  internal/notifier/alertmanager.go
Labels: area/alerting
