Repository fluxcd/notification-controller, pull requests merged in 2025-04, with the labels that each got.

#1093 Sanitize proxy error logging
  internal/server/event_handlers.go
Labels: backport:release/v1.5.x

#1087 feat: add 'proxyURL' support to Gitea notifier
  go.mod
  go.sum
  internal/notifier/factory.go
  internal/notifier/gitea.go
  internal/notifier/gitea_test.go
  tests/listener/listener.go
  tests/proxy/proxy.go
Labels: area/alerting

#1104 Update to Kubernetes 1.33.0 and Go 1.24.0
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yml
  DEVELOPMENT.md
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  tests/fuzz/Dockerfile.builder
Labels: dependencies
