Repository fluxcd/notification-controller, pull requests merged in 2025-01, with the labels that each got.

#1016 Migrate to `gitlab.com/gitlab-org/api/client-go`
  go.mod
  go.sum
  internal/notifier/gitlab.go
Labels: dependencies

#1014 [RFC-0008] Custom Event Metadata from Annotations
  api/v1beta3/alert_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  docs/api/v1beta3/notification.md
  docs/spec/v1beta3/alerts.md
  go.mod
  go.sum
  internal/server/event_handlers.go
  internal/server/event_handlers_test.go
  internal/server/event_server.go
  internal/server/event_server_test.go
Labels: enhancement, area/alerting, area/api

#1017 msteams notifier: adaptive cards full width
  internal/notifier/teams.go
  internal/notifier/teams_test.go
Labels: area/alerting

#1018 Add support for MetaOriginRevisionKey from the Event API
  go.mod
  go.sum
  internal/notifier/azure_devops.go
  internal/notifier/azure_devops_test.go
  internal/notifier/bitbucket.go
  internal/notifier/bitbucketserver.go
  internal/notifier/bitbucketserver_test.go
  internal/notifier/gitea.go
  internal/notifier/gitea_test.go
  internal/notifier/github.go
  internal/notifier/gitlab.go
  internal/server/event_server.go
  internal/server/event_server_test.go
Labels: area/alerting

#1019 Add subsection for Git providers supporting commit status updates
  docs/spec/v1beta3/providers.md
Labels: area/docs

#1022 Enforce namespace check on receiver
  docs/spec/v1/receivers.md
  internal/controller/receiver_controller_test.go
  internal/server/receiver_handler_test.go
  internal/server/receiver_handlers.go
  internal/server/receiver_server.go
  main.go
Labels: area/receiver

#1010 fix: adding of duplicate commit statuses in gitlab
  internal/notifier/gitlab.go
Labels: area/alerting
