Repository fluxcd/notification-controller, pull requests merged in 2025-05, with the labels that each got.

#1106 [RFC-0010] Implement managed identity support for Azure Event Hub provider
  api/v1beta3/provider_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
  config/rbac/role.yaml
  docs/api/v1beta3/notification.md
  docs/spec/v1beta3/providers.md
  go.mod
  go.sum
  internal/controller/provider_controller.go
  internal/notifier/azure_eventhub.go
  internal/notifier/azure_eventhub_test.go
  internal/notifier/factory.go
  internal/notifier/github_helpers.go
  internal/notifier/notifier.go
  internal/server/event_handlers.go
  main.go
Labels: area/alerting

#1118 Update controller-runtime to v0.21.0
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#1119 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#1120 [RFC-0010] Link workload identity docs to complete guide
  docs/spec/v1beta3/providers.md
Labels: area/docs

#1108 CrossNamespaceObjectReference: Fix MaxLength validation to k8s max 253 char
  api/v1/reference_types.go
  config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml
  config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
Labels: area/api

#1127 Update dependabot config
  .github/dependabot.yaml
Labels: area/ci
